#!/usr/bin/env bash

bg_clone() {
  >&2 echo "Cloning $1..."
  git clone "$1" &>/dev/null &
}

# Init packages
for package in code extend filenav integrate theme; do
  mkdir -p "$HOME/.vim/pack/$package"/{start,opt}
done

# Clone plugins
cd "$HOME/.vim/pack/theme/start" && {
  bg_clone https://github.com/romainl/Apprentice
}

cd "$HOME/.vim/pack/extend/start" && {
  bg_clone https://github.com/FooSoft/vim-argwrap
  bg_clone https://github.com/tpope/vim-repeat.git
  bg_clone https://github.com/tpope/vim-surround
}

cd "$HOME/.vim/pack/filenav/start" && {
  bg_clone https://github.com/tpope/vim-vinegar.git
}

cd "$HOME/.vim/pack/integrate/start" && {
  bg_clone https://github.com/tpope/vim-fugitive.git
}

# Finish up
wait
>&2 echo "Done."
